context.annotation.value.empty=Property "value" is missing on the annotation @org.kaleidofoundry.core.context.Context 

context.annotation.illegaluse.noRuntimeContextField=Field "{0}" is "{1}" annotated, but its class does not contains org.kaleidofoundry.core.context.RuntimeContext<?> field.
context.annotation.illegalinject=Context "{0}" has already been injected.
context.annotation.illegalfield=org.kaleidofoundry.core.context.RuntimeContext field "{0}#{1}" is final and null, it can''t be injected.
context.annotation.illegalconfig.simple=Illegal configuration definition in annotation @org.kaleidofoundry.core.context.Context(value="{0}", configurations=''{''..,"{1}",..''}''). The configuration "{1}" may not have been registered ?
context.annotation.missing=Missing annotation @org.kaleidofoundry.core.context.Context on field / argument "{0}"

context.parameter.empty=Parameter "{0}" have to be set in context "{1}"
context.parameter.causes.error=Parameter "{0}={1}" in context "{2}" causes error: "{3}"
context.parameter.illegal.use=Illegal use of parameter "{0}={1}" in context "{2}", reason: "{3}"

# introspection error
context.provider.error.NoSuchConstructorException=Class "{0}" must define a constructor with signature: {0}({1})
context.provider.error.InstantiationException=Class "{0}" can''t be instantiate due to underlying error: "{1}"
context.provider.error.IllegalAccessException=Class "{0}" must define an accessible constructor with signature: {0}({1})
context.provider.error.InvocationTargetException=Error calling constructor "{0}({1})". Please check traces.

context.provider.error.default=Provider encountered an unexpected error. Please have a look on the nested exception.